# Generated by Django 4.1.7 on 2023-03-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
