# Generated by Django 4.1.7 on 2023-03-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=5)),
            ],
        ),
    ]
